name: Run Braintrust Evals

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  eval:
    name: Run evals
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install Dependencies
        id: install
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run Evals
        uses: braintrustdata/eval-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.BRAINTRUST_API_KEY }}
          runtime: node
          root: evals