name: Run Braintrust Evals

on:
    workflow_dispatch:
    pull_request:

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  eval:
    name: Run evals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install Dependencies
        id: install
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run Evals
        id: evals
        run: yarn tsx evals/llm.evals.ts

      - name: Add Evals Report to Github Comment
        if: always()
        run: echo "$(cat llm.evals.md)" >> $GITHUB_STEP_SUMMARY
        